# Generated by Django 5.1.2 on 2024-10-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_message_date_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='firstquestion',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='account',
            name='secondquestion',
            field=models.TextField(default='null'),
        ),
    ]
